### ISSUE TITLE
Bug PropTypes and BackAndroid is deprecated

### ISSUE THREAD

**Issue by Angelk90** [zhengxiaoyao0716/react-native-modal-dialog#2]
@zhengxiaoyao0716 : 
1.
Starting the module, from problems in line 9 of the index.js file.
I solved the problem by changing:
import React, {Component, Children, PropTypes} from 'react';

with

import React, {Component, Children} from 'react';
import PropTypes from 'prop-types';

2.
Starting the module says that BackAndroid is deprecated recommends replacing with:
BackHandler Instead.

Version react-native: v0.49

**Comment by zhengxiaoyao0716** [comment]
Thanks @karchz, this problem is already fixed long ago. [pull-request/1](https://github.com/zhengxiaoyao0716/react-native-modal-dialog/pull/1)
But I'm sorry that I forgot to publish a new version package.
I catch up it and you can get it now, just update it: `npm update --save react-native-modal-dialog`
Thanks for your issue.

**Comment by zhengxiaoyao0716** [comment]
Well, PropTypes fix too, use version 1.2.0

**Comment by Angelk90** [comment]
@zhengxiaoyao0716 : 
It would be possible to give the possibility to change the title of the dialog, from "Promp" to "Something else" in a dynamic way.
And also change the color of the modal.

P.Š.
To take a text field from a Prompt, I had to do something like that.
But it does not seem to me a very correct form, because every time it changes that a letter is inserted or deleted, the setState is called in this case, and it is not a very optimal thing.
```
        this.refs.dialog.prompt("","",(t) => {
          this.setState({url:t});
        },{
          onPosClick:() => {
            this.refs.dialog.hide();
            AsyncStorage.setItem('url',this.state.url);
            this.search("");
          }
        });
```

**Comment by zhengxiaoyao0716** [comment]
@Angelk90 just override the props you need. For example, use `prompt(message, placeholder, onChangeText, { title: 'Custom Title', modalStyle: { backgroundColor: '#6cf' }})`.
![image](https://user-images.githubusercontent.com/12682063/34256174-05e086b6-e68f-11e7-9792-fc51b11c4b22.png)
![image](https://user-images.githubusercontent.com/12682063/34256154-ec72a1aa-e68e-11e7-964e-3d0de78d0044.png)

And for the usage that call `setState` in `onChangeText`, it is given by official: http://facebook.github.io/react-native/docs/handling-text-input.html

**Comment by Angelk90** [comment]
@zhengxiaoyao0716 : 
Reading the ReadMe:
It is not explained that they exist:
```
        title: PropTypes.string,
        message: PropTypes.string,
        negText: PropTypes.string,
        onNegClick: PropTypes.func,
        posText: PropTypes.string,
        onPosClick: PropTypes.func,
        onCancel: PropTypes.func,
        dialogStyle: StyleSheetPropType,
        modalStyle: StyleSheetPropType,
        contentStyle: StyleSheetPropType,
        titleStyle: StyleSheetPropType,
        messageStyle: StyleSheetPropType,
        buttonBarStyle: StyleSheetPropType,
        buttonStyle: StyleSheetPropType,
```

and How they work, we need to see the code of the index file and the proposed example, to know that they exist.

Instead of using the `onChangeText `method, I thought more than doing a `ref `on the input field, and in this case for example `onPosClick `could return the text.

```
          onPosClick: (result) => {
result.text
```

**Comment by zhengxiaoyao0716** [comment]
I'm sorry that I should provide a more details document, but my English is poor and have no confidence to writing them clearly, will you post a pull-request? I'll be grateful.
Return the text with `onPosClickcould` is a nice idea, if we don't need to update the state if other component in real-time. But recently I'm a bit busy, I'm wonder that can I ask you for help to make contribution for it... Anywhere, thanks for your suggest.
