### ISSUE TITLE
Failed prop type: Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by 12343954** [zhengxiaoyao0716/react-native-modal-dialog#3]
`contentStyle={{ backgroundColor: 'black' }} ` will show this error tip

![image](https://user-images.githubusercontent.com/1804003/35317667-d8438d40-0112-11e8-9b81-1238418c8ec4.png)

![image](https://user-images.githubusercontent.com/1804003/35317695-f05e97c6-0112-11e8-9de4-deec4d4a2580.png)

![image](https://user-images.githubusercontent.com/1804003/35317712-09b510f6-0113-11e8-9a57-a6b2c7875464.png)

```
"react": "16.0.0",
"react-native": "0.50.3",
"react-native-modal-dialog": "^1.2.1",
```

**Comment by zhengxiaoyao0716** [comment]
看起来是 `Object instanceof StyleSheet` 出的问题，可以尝试把传入的style的Object换成StyleSheet创建出来的对象。或者升级RN版本，我在RN0.51.0上测试你的写法时得到了一个警告，但没有报错。你可以先试试，我也尝试用RN0.50.3再测一下，等会儿告诉你结果。

**Comment by zhengxiaoyao0716** [comment]
抱歉，我在相同环境下进行了测试，但仍然只得到了一个警告：
![image](https://user-images.githubusercontent.com/12682063/35318953-afdba0b2-0118-11e8-9171-2313f853977c.png)
我会尝试去掉这个警告，但你的报错看来是其它原因引起的，我无能为力。或者你能再提供些其它更具体的信息？

**Comment by zhengxiaoyao0716** [comment]
我已经解决了这个警告，请尝试1.2.2版本。
另外我在Example里添加了[针对这个问题的测试](https://github.com/zhengxiaoyao0716/react-native-modal-dialog/commit/9be9ba7f11e0a1473a062c3451533f0be627ecd9) 。如果还是有这个报错，你可以尝试跑一下[Example](https://github.com/zhengxiaoyao0716/react-native-modal-dialog/tree/master/ReactNativeModalDialog).

**Comment by 12343954** [comment]
good job ！ thank you so much ，I will try
