### ISSUE TITLE
Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by lekeCoder** [zhengxiaoyao0716/react-native-modal-dialog#4]
![simulator screen shot - iphone 6 - 2018-07-18 at 14 40 32](https://user-images.githubusercontent.com/19432914/42885363-af5eadaa-8a98-11e8-8811-05ff99c0d609.png)
React Native: 0.56
React: 16.3.1

**Comment by zhengxiaoyao0716** [comment]
Hello, I make an [online preview example](https://snack.expo.io/@zhengxiaoyao0716/github.com-zhengxiaoyao0716-react-native-modal-dialog:reactnativemodaldialog) and have not got the error, could you provide more details?

**Comment by 12343954** [comment]
@lekeCoder I fixed it ! 

"react": "16.4.1",
"react-native": "0.56.0",

in /node_modules/react-native-modal-dialog/index.js

1, import { ViewPropTypes } from 'react-native'
2, replace in line 9
// const StylePropType = View.propTypes.style;
const StylePropType = ViewPropTypes.style;

could you please update your code ? @zhengxiaoyao0716

**Comment by zhengxiaoyao0716** [comment]
@12343954 Nice job, would you like to make a pull request?

**Comment by 12343954** [comment]
haha ,sorry , 我不会用GitHub提PR，我试过了，没成功！

**Comment by zhengxiaoyao0716** [comment]
最简单的方法就是直接在GitHub上[edit](https://github.com/zhengxiaoyao0716/react-native-modal-dialog/edit/master/index.js)，保存的时候选择Pull Request

**Comment by 12343954** [comment]
好的，我试试
